name: composer
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/samlet/composer

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  logging: ^1.0.2
  path: ^1.8.0
  #  quartet: ^0.1.1
  recase: ^4.0.0
  args: ^2.3.0
  jinja: ^0.4.0-dev.31
  bluecc_srv:
    path: ../bluecc_srv
  hubs_data:
    path: ../hubs_data
  mqtt_client: ^9.6.8


dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
